title: "[Problem] "
labels: ["General Problems"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to start a new discussion!
  - type: textarea
    id: newQuestion
    attributes:
      label: Question
      description: "If there's any problem or suggestion, please let us know!"
      value: |
        - Problem Number: ...
        - Problem Statement: ...
        - Problem Target: ...
        - 
      render: bash
    validations:
      required: true
