# title: "[Suggestion] "
# labels: ["General suggestion"]
# body:
#   - type: markdown
#     attributes:
#       value: |
#         Thanks for taking the time to start a new discussion and giving us suggestions!
#         However, please follow the rules:
#         ❗️ If you have any question for solving the problem, please head to **Ask for Help** category. ❗️
#         ❗️ If you have any suggestion or idea for solutions of problems, please head to **New Idea** category. ❗️
#   - type: textarea
#     id: newSuggestion
#     attributes:
#       label: hihi
#       description: "Please feel free to give us any suggestion!"
#         - Suggestion: ...
        
#       render: bash
#     validations:
#       required: true


title: "[Suggestion] "
labels: ["General suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to start a new discussion and giving us suggestions!
        However, please follow the rules:
        ❗️ If you have any ideas for the solution of the problem, please head to **New Idea** category. ❗️
        ❗️ If you have any suggestion for us, please head to **Suggestion** category. ❗️
  - type: textarea
    id: newSuggestion
    attributes:
      label: suggestion
      description: "If there's any trouble solving the problem, please feel free to ask!"
      value: |
        - Problem Number: ...
        - Problem Statement and Targets: ...
        
        - Describe the bug or your question: ...
        
        - Paste your judging results: ...
        
      render: bash
    validations:
      required: true
